### ISSUE TITLE
Converted files don't appear on branch

### ISSUE THREAD

**Issue by thgie** [sharadcodes/img-resizer#2]
Hello there!

Could you help me out here? I'm trying to integrate the resize action but seem to do something wrong: https://github.com/thgie/zk-tapt/blob/master/.github/workflows/publish.yml. The converted files don't appear on the branch, respectively, it doesn't find the input folder to begin with.

Thanks for the great work :)

**Comment by sharadcodes** [comment]
Hi @thgie 
See you'll have to use the git push in the workflow. Since the resizing action is only for performing conversion & not updating the repo.
You can add something like this
```yml
    - name: Add & Commit files
      run: |
        git config --local user.email "your-github-username@github.com"
        git config --local user.name "your-github-username"
        git add .
        git commit -m "Add changes" -a
        git push -f -q https://${{ secrets.GITHUB_TOKEN }}@github.com/your-github-username/YOUR-REPO-NAME.git master
```

**Comment by thgie** [comment]
The following deploy action takes care of that. It basically pushes to the gh-pages branch. https://github.com/s0/git-publish-subdir-action

**Comment by sharadcodes** [comment]
Is it working after using that action @thgie

**Comment by sharadcodes** [comment]
@thgie ?

**Comment by thgie** [comment]
Sorry, I didn't get a notification for your last message. I already used that action before, but it doesn't help :|

**Comment by sharadcodes** [comment]
Try my code @thgie
